# Generated by Django 2.1.1 on 2018-09-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_salas', '0002_sala_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='teste',
        ),
    ]
