# Generated by Django 2.1.1 on 2018-09-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_salas', '0003_remove_sala_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='quantidade_pessoas',
            field=models.IntegerField(default=0),
        ),
    ]
